### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by gokhandilek** [oauthjs/express-oauth-server#25]
Just wondering if anyone had success running this application?

```
node-oauth2-server-implementation-master/components/oauth/sqldb/OAuthAccessToken.js:8
  const OAuthAccessToken = sequelize.define('OAuthAccessToken', {
  ^^^^^

SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)


```

**Comment by ruimarinho** [comment]
This is not related to this module. You're likely missing `use strict` at the top of the module or you need to upgrade to a newer node version.
