### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by gupta-vaibhav** [oauthjs/express-oauth-server#80]
I have created the server verbatim (I think), but still not able to use it. When I am trying to get the access token using a password grant, I keep getting the subject error.

I am using Postman to POST the request as follows:
```
Address: localhost:3000/oauth/token
Header: {Content-Type: application/x-www-form-urlencoded, Authorization: __________}
Body: {grant_type: password, username: _____, password: ______}
```

However the error that I keep getting is:
```
server_error: Cannot read property '0' of undefined
    at new ServerError (/Users/vaibhavgupta/games/pool/server/data/microservices/node_modules/express-oauth-server/node_modules/oauth2-server/lib/errors/server-error.js:25:14)
    at TokenHandler.<anonymous> (/Users/vaibhavgupta/games/pool/server/data/microservices/node_modules/express-oauth-server/node_modules/oauth2-server/lib/handlers/token-handler.js:102:13)
From previous event:
    at TokenHandler.handle (/Users/vaibhavgupta/games/pool/server/data/microservices/node_modules/express-oauth-server/node_modules/oauth2-server/lib/handlers/token-handler.js:100:13)
    at OAuth2Server.token (/Users/vaibhavgupta/games/pool/server/data/microservices/node_modules/express-oauth-server/node_modules/oauth2-server/lib/server.js:75:6)
    at ExpressOAuthServer.<anonymous> (/Users/vaibhavgupta/games/pool/server/data/microservices/node_modules/express-oauth-server/index.js:113:28)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

Will much much appreciate any help that I can get..

**Comment by gupta-vaibhav** [comment]
Just in case anyone else faces the same issue, here are a number of changes that I had to do:

```
pg.query(...).then(function(result){
    // In here, result itself is the array of resulting rows, not result.rows. Further, since results contains the array or rows itself, result.rowCount doesn't exist. Modified code accordingly.
})

```
Secondly, the data structure in getRefreshToken is not the same as that required eventually in the other modules. Had to correct the structure as follows:

```
module.exports.getRefreshToken = function *(bearerToken) {
    return pg.query('SELECT access_token, access_token_expires_on, client_id, refresh_token, refresh_token_expires_on, user_id FROM oauth_tokens WHERE refresh_token = $1', [bearerToken])
        .then(function(result) {
            var data = {};
            data.accessToken = result[0].access_token;
            data.accessTokenExpiresAt = result[0].access_token_expires_on;
            data.client = result[0].client_id;
            data.refreshToken = result[0].refresh_token;
            data.refreshTokenExpiresAt = result[0].refresh_token_expires_on;
            //data.scope = ??????;
            data.user = result[0].user_id;

            return data.refreshToken ? data : false; // TODO return object with client: {id: clientId} and user: {id: userId} defined
        });
};

```

Finally, a bunch of changes in saveToken, highlighted as comments below:

```
module.exports.saveToken = function *(token, client, user) {
    return pg.query("INSERT INTO oauth_tokens(access_token, access_token_expires_on, client_id, refresh_token, refresh_token_expires_on, user_id) VALUES ($1, $2, $3, $4, $5, $6 /*added $5, $6*/) RETURNING * /*Returning * is required since without it INSERT returns no data. */", [
        token.accessToken,
        token.accessTokenExpiresAt,
        client.clientId, //should be client.clientId, instead of client.id
        token.refreshToken,
        token.refreshTokenExpiresAt,
        user.id
    ]).then(function(result) {

        // Changed this entire piece to make it compatible with the rest of the code.
        var data = {};
        data.accessToken = result[0].access_token;
        data.accessTokenExpiresAt = result[0].access_token_expires_on;
        data.client = result[0].client_id;
        data.refreshToken = result[0].refresh_token;
        data.refreshTokenExpiresAt = result[0].refresh_token_expires_on;
        //data.scope = ??????;
        data.user = result[0].user_id;

        return data.accessToken ? data : false; // TODO return object with client: {id: clientId} and user: {id: userId} defined
    });
};
```
